# Use the official Node.js image as a base image
FROM node:20

# Set the working directory in the container
WORKDIR /app/client

# Copy package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 3001
EXPOSE 3001

# Define environment variables
ENV MONGO_URI=mongodb+srv://robins57:Bruh5@fullstackproject.nhzv5ms.mongodb.net/?retryWrites=true&w=majority&appName=FullStackProject
#ENV JWT_KEY=15e281e043b9e4f4b2ee0073e2635eba4fab2f237e82a63a766578ff6d7de345

# Define the command to run the Express app
CMD ["npm", "run", "dev"]